---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ride-companion-dev
  name: ride-companion-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ride-companion-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ride-companion-dev
    spec:
      containers:
        - name: ride-companion-dev
          image: ride-companion:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: 5000
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "2048Mi"
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ride-companion-dev
spec:
  ports:
    - port: 80
      name: http
      targetPort: 5000
  selector:
    app: ride-companion-dev